[build]
  publish = "."
  functions = "netlify/functions"

# Support for the "Drop Folder" dashboards
[[redirects]]
  from = "/dashboards/*"
  to = "/dashboards/:splat"
  status = 200

# General SPA redirect (keeps the React app working on refresh)
# This MUST stay at the bottom
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200